"""empty message

Revision ID: fed65154fba4
Revises: dfb60f109d54
Create Date: 2018-09-27 10:28:06.196121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed65154fba4'
down_revision = 'dfb60f109d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'state')
    # ### end Alembic commands ###
